server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://b9ab8e76f9f303:6a46bf38@us-cdbr-east-06.cleardb.net/heroku_ee6fe0a8bca57f0?reconnect=true
    username: b9ab8e76f9f303
    password: 6a46bf38
  jpa:
    show-sql: true
